baseurl = "https://meptrsn.github.io/blog/"
title = "meptrsn"
languageCode = "en-us"

[params]

# your name to display by the copyright sign
# default: undefined
AuthorName = "Matthew Petersen"

# tagline to show beneath homepage h1
# default: undefined
Tagline = "Engineering, Assyriology, and games."

# number of posts to show on index
# default: 10
HomepagePosts = 10

# if set to true, social links will be displayed in the footer
# default: undefined
SocialLinks = true

# default: undefined
GithubUsername = "petersme"

# default: undefined
TwitterUsername = "meptrsn"
