baseurl = "https://meptrsn.info/blog"
languageCode = "en-us"
theme = "paperback"
title = "Letters"
[params]
authorname = "Matthew Petersen"
githubusername = "meptrsn"
homepageposts = 10
sociallinks = true
tagline = "Engineering, Assyriology, and games."
twitterusername = "meptrsn"
[taxonomies]
category = "categories"
tag = "tags"
